<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Mateu.Demo</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Mateu.AspNetCore/Mateu.AspNetCore.csproj" />
    <ProjectReference Include="../../src/Mateu.Uidl/Mateu.Uidl.csproj" />
  </ItemGroup>
</Project>
