[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/fluent/mateu"
to = "https://demo.mateu.io"
status = 200
force = true
headers = {X-From = "Netlify"}

[[redirects]]
from = "/fluent/mateu"
to = "https://demo.mateu.io"
status = 200
force = true
headers = {X-From = "Netlify"}

[[redirects]]
from = "/mateu"
to = "https://demo.mateu.io"
status = 200
force = true
headers = {X-From = "Netlify"}

[[redirects]]
from = "/images"
to = "https://demo.mateu.io"
status = 200
force = true
headers = {X-From = "Netlify"}
