import type { CanvasRendererId } from '../canvas/canvasRenderer'

/**
 * The palette thumbnails, per canvas renderer: real screenshots of each component as that renderer
 * paints it, generated by `scripts/thumbnails.mjs` (never drawn by hand). Vite resolves the glob at
 * build time, so a missing file simply means "no thumbnail" — the palette then shows the name only.
 * The DS-neutral canvas has none on purpose: a Lumo picture over a neutral canvas would mislead.
 */
const byType = (files: Record<string, string>): Record<string, string> =>
    Object.fromEntries(Object.entries(files).map(([path, url]) => [path.slice(path.lastIndexOf('/') + 1).replace(/\.png$/, ''), url]))

const THUMBNAILS: Partial<Record<CanvasRendererId, Record<string, string>>> = {
    vaadin: byType(import.meta.glob('../thumbnails/vaadin/*.png', { eager: true, query: '?url', import: 'default' }) as Record<string, string>),
}

/** The thumbnail URL for a component under a renderer, or undefined when there is none. */
export function thumbnailUrl(renderer: CanvasRendererId, type: string): string | undefined {
    return THUMBNAILS[renderer]?.[type]
}

/** The component types that have a thumbnail under a renderer. */
export function thumbnailTypes(renderer: CanvasRendererId): string[] {
    return Object.keys(THUMBNAILS[renderer] ?? {}).sort()
}
