import type { CanvasRendererId } from '../canvas/canvasRenderer'

/**
 * The palette thumbnails, per design system: real screenshots of each component as that renderer
 * paints it, generated by `scripts/thumbnails.mjs` (never drawn by hand). Vite resolves the globs at
 * build time, so a missing file simply means "no thumbnail" — the palette then shows the name only.
 *
 * - `vaadin`: what the canvas paints. Every component has one or a NO_THUMBNAIL reason (tested).
 * - `redwood`: what the Redwood (VB) renderer paints. The canvas cannot run it, so this is the only
 *   preview of a Redwood app inside the editor — and a component with no Redwood thumbnail is one the
 *   Redwood renderer most likely does not paint, which is worth knowing before you drop it.
 */
export type ThumbnailLook = 'vaadin' | 'redwood'

export const THUMBNAIL_LOOKS: ThumbnailLook[] = ['vaadin', 'redwood']

export const THUMBNAIL_LOOK_LABELS: Record<ThumbnailLook, string> = { vaadin: 'Vaadin', redwood: 'Redwood' }

const byType = (files: Record<string, string>): Record<string, string> =>
    Object.fromEntries(Object.entries(files).map(([path, url]) => [path.slice(path.lastIndexOf('/') + 1).replace(/\.png$/, ''), url]))

const THUMBNAILS: Record<ThumbnailLook, Record<string, string>> = {
    vaadin: byType(import.meta.glob('../thumbnails/vaadin/*.png', { eager: true, query: '?url', import: 'default' }) as Record<string, string>),
    redwood: byType(import.meta.glob('../thumbnails/redwood/*.png', { eager: true, query: '?url', import: 'default' }) as Record<string, string>),
}

/** The thumbnail URL for a component in a look, or undefined when there is none. */
export function thumbnailUrl(look: ThumbnailLook, type: string): string | undefined {
    return THUMBNAILS[look]?.[type]
}

/** The component types that have a thumbnail in a look. */
export function thumbnailTypes(look: ThumbnailLook): string[] {
    return Object.keys(THUMBNAILS[look] ?? {}).sort((a, b) => a.localeCompare(b))
}

/**
 * The look the palette starts with: the canvas's own design system, or none for the DS-neutral
 * canvas (a Lumo picture over a neutral canvas would mislead). Redwood is only ever an explicit pick.
 */
export function defaultLook(canvas: CanvasRendererId): ThumbnailLook | 'none' {
    return canvas === 'vaadin' ? 'vaadin' : 'none'
}
