/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.mateu.java-conventions")
}

dependencies {
    api(project(":dtos"))
    api(project(":annotation-processing"))
    api("com.opencsv:opencsv:5.7.1")
    api("org.apache.poi:poi:5.2.3")
    api("org.apache.poi:poi-ooxml:5.2.3")
    api("jakarta.persistence:jakarta.persistence-api:3.1.0")
    //api("org.projectlombok:lombok:1.18.24")
    compileOnly("org.projectlombok:lombok:1.18.30")
    annotationProcessor("org.projectlombok:lombok:1.18.30")

    testCompileOnly("org.projectlombok:lombok:1.18.30")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.30")

    api("org.slf4j:slf4j-api:2.0.4")
    api("com.google.guava:guava:33.0.0-jre")
    api("commons-beanutils:commons-beanutils:1.9.4")
    api("org.hibernate.validator:hibernate-validator:8.0.0.Final")
    api("io.projectreactor:reactor-core:3.5.4")
    api("com.google.auto.service:auto-service:1.0.1")
    api("com.fasterxml.jackson.core:jackson-core:2.15.2")
    api("com.fasterxml.jackson.core:jackson-databind:2.15.2")
    api("com.fasterxml.jackson.core:jackson-annotations:2.15.2")
    api("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.15.2")
    api("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.15.2")
    api("org.jdom:jdom2:2.0.6.1")
    api("jaxen:jaxen:1.2.0")
    api("com.github.slugify:slugify:2.2")
    api("com.google.http-client:google-http-client:1.34.0")
    api("com.google.http-client:google-http-client-jackson2:1.32.1")
    api("jakarta.el:jakarta.el-api:5.0.1")
    api("org.glassfish.expressly:expressly:5.0.0")
    api("org.reflections:reflections:0.9.11")
    testImplementation("io.projectreactor:reactor-test:3.6.1")
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.0.5")
    compileOnly("org.springframework.boot:spring-boot-starter-webflux:3.0.5")
    compileOnly("org.springframework.boot:spring-boot-starter-data-jpa:3.0.5")
}

description = "core"

java {
    withJavadocJar()
}
