export enum ActionTarget {
    Self = "Self",
    View = "View",
    Message = "Message",
    NewModal = "NewModal",
    NewTab = "NewTab",
    NewWindow = "NewWindow",
    LeftDrawer = "LeftDrawer",
    RightDrawer = "RightDrawer",
    NewJourney = "NewJourney",
    Deferred = "Deferred",
    DeferredNewTab = "DeferredNewTab",
    DeferredNewWindow = "DeferredNewWindow",
    Component = "Component",
    Header = "Header",
    Footer = "Footer",
    Main = "Main",
    Left = "Left",
    Right = "Right"
}
