package com.example.demo;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

import java.util.Map;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.containsString;

/**
 * Boots the real application and exercises mateu over HTTP, to prove that quarkus needs no
 * special setup: every mateu bean comes from the io.mateu:quarkus-core jar and the controllers
 * are generated by the annotation processor, with a plain javac compile.
 */
@QuarkusTest
class MateuHttpE2eTest {

    @Test
    void indexIsServedForUiRoute() {
        given()
                .when().get("/counter")
                .then()
                .statusCode(200)
                .body(containsString("<mateu-ui baseUrl=\"/counter\""));
    }

    @Test
    void spaSubRouteServesTheSameIndex() {
        given()
                .when().get("/counter/section1")
                .then()
                .statusCode(200)
                .body(containsString("<mateu-ui baseUrl=\"/counter\""));
    }

    @Test
    void initialLoadReturnsTheComponentTree() {
        given()
                .contentType("application/json")
                .body(runActionPayload(""))
                .when().post("/counter/mateu/v3/x")
                .then()
                .statusCode(200)
                .body(containsString("\"serverSideType\":\"com.example.demo.Counter\""))
                .body(containsString("\"label\":\"Increment\""));
    }

    @Test
    void runActionExecutesTheActionAndReturnsTheNewState() {
        given()
                .contentType("application/json")
                .body(runActionPayload("increment"))
                .when().post("/counter/mateu/v3/x")
                .then()
                .statusCode(200)
                .body(containsString("\"count\":1"));
    }

    private static Map<String, Object> runActionPayload(String actionId) {
        return Map.of(
                "componentState", Map.of(),
                "appState", Map.of(),
                "parameters", Map.of(),
                "actionId", actionId,
                "route", "/counter",
                "serverSideType", "com.example.demo.Counter");
    }
}
