/**
 * Boots the Redwood Spectra renderer.
 *
 * The Oracle JET / Spectra web components (oj-c-*, oj-sp-*) are AMD modules served from Oracle's
 * public CDN as BUNDLES (a require() for e.g. `ojs/ojbootstrap` resolves to the bundle file that
 * contains it). We load Oracle's own RequireJS bundle configs FROM the CDN — never copied here —
 * so the require paths + bundle map are always Oracle's authoritative ones. Then Vite serves our
 * own code as ES modules; this file bridges the two:
 *
 *   1. load RequireJS from the CDN,
 *   2. load the JET bundle config (configures ojs/* and oj-c/*) and the Spectra bundle config
 *      (configures oj-sp/*) — both self-execute requirejs.config against the CDN,
 *   3. add the missing `oj-sp` path (the Spectra config only ships the bundle map, no paths),
 *   4. require OJET's base plus EVERY oj-c/oj-sp module the renderer uses, so all custom
 *      elements are defined before the first Lit render; the ArrayDataProvider class and the
 *      ready flag are stashed on window.__mateuOj for the renderer modules,
 *   5. import our ES-module entry (registers <mateu-ui> + the Redwood renderer),
 *   6. adopt the routed <mateu-ui> into #ui-container (or create one from the URL path when the
 *      page was not generated by the AP controllers) and reveal it.
 *
 * If the CDN can't be reached the app still boots: window.__mateuOj.ready stays false and the
 * renderer delegates everything to the shared base renderer (graceful degradation).
 */

// Oracle CDN coordinates — the exact versions the Spectra Shell uses (bump together to move JET /
// Spectra). NOTE the JET version carries the build suffix (…-2604.8): the bundle files only exist
// under that path.
const JET_BASE = 'https://static.oracle.com/cdn/jet/19.0.0-2604.8'
const REQUIRE_JS = `${JET_BASE}/3rdparty/require/require.js`
const JET_BUNDLE_CONFIG = `${JET_BASE}/default/js/bundles-config.js`
const SPECTRA_VERSION = '2604.1.0'
const SPECTRA_BUNDLE_CONFIG = `https://static.oracle.com/cdn/spectra-ui/oj-sp/${SPECTRA_VERSION}/oj-sp-bundle-config.js`

// Every AMD module the renderer needs. Loading them all up-front means the custom elements are
// defined before <mateu-ui> mounts, and no component ever pops in late.
//  - ojs/ojknockout: the oj-sp pack components are Knockout-era composites whose templates use
//    oj-bind-text / oj-bind-if — without this module their bindings never resolve.
//  - ojs/ojarraydataprovider: exports the ArrayDataProvider CLASS as the module value itself
//    (ojs/ojdataprovider in JET 19 only carries operators/utils).
const OJ_MODULES = [
  'ojs/ojbootstrap',
  'ojs/ojknockout',
  'ojs/ojarraydataprovider',
  'ojs/ojchart',
  'ojs/ojswitch',
  'ojs/ojslider',
  'ojs/ojmenu',
  // oj-c (preact VComponents)
  'oj-c/button',
  'oj-c/menu-button',
  'oj-c/input-text',
  'oj-c/input-number',
  'oj-c/input-password',
  'oj-c/text-area',
  'oj-c/select-single',
  'oj-c/select-multiple',
  'oj-c/radioset',
  'oj-c/checkboxset',
  'oj-c/checkbox',
  'oj-c/input-date-picker',
  'oj-c/input-time-mask',
  'oj-c/file-picker',
  'oj-c/rating-gauge',
  'oj-c/form-layout',
  'oj-c/collapsible',
  'oj-c/tab-bar',
  'oj-c/table',
  'oj-c/list-view',
  'oj-c/badge',
  'oj-c/progress-bar',
  'oj-c/meter-bar',
  'oj-c/skeleton',
  'oj-c/dialog',
  'oj-c/avatar',
  'oj-c/line-chart',
  // oj-sp (Spectra pack)
  'oj-sp/messages-manager/loader',
  'oj-sp/metric-card/loader',
  'oj-sp/empty-state/loader',
  'oj-sp/welcome-page/loader',
  'oj-sp/header-welcome-banner/loader',
  'oj-sp/foldout-layout/loader',
  'oj-sp/foldout-panel/loader',
  'oj-sp/scoreboard/loader',
  'oj-sp/dashboard-panel/loader',
  'oj-sp/in-app-navigation/loader',
]

declare global {
  interface Window {
    require?: any
    requirejs?: any
    __mateuOj?: {
      ready: boolean
      ArrayDataProvider?: any
      require?: any
    }
  }
}

const loadScript = (src: string): Promise<void> =>
  new Promise((resolve, reject) => {
    const s = document.createElement('script')
    s.src = src
    s.async = false
    s.onload = () => resolve()
    s.onerror = () => reject(new Error('failed to load ' + src))
    document.head.appendChild(s)
  })

/** Adopt the routed <mateu-ui> (injected by the AP controllers into the inert template) into the
 * live #ui-container; when the page was NOT generated by the controllers (plain dev server),
 * create a <mateu-ui> that resolves the route from the URL path. Then reveal it. */
async function mountLitRoot() {
  await import('@/index')
  const container = document.getElementById('ui-container')
  const holder = document.getElementById('mateu-ui-holder') as HTMLTemplateElement | null
  if (container && holder && holder.content.childElementCount > 0) {
    container.appendChild(holder.content.cloneNode(true))
  } else if (container && !container.querySelector('mateu-ui')) {
    const ui = document.createElement('mateu-ui')
    ui.setAttribute('baseUrl', '')
    ui.setAttribute('urlPrefix', '')
    container.appendChild(ui)
  }
  if (container) container.style.display = ''
  document.getElementById('landing-loader')?.remove()
}

async function loadOjet() {
  await loadScript(REQUIRE_JS)
  // Oracle's own require configs (paths + bundle map). They self-execute requirejs.config against
  // absolute CDN URLs.
  await loadScript(JET_BUNDLE_CONFIG)
  await loadScript(SPECTRA_BUNDLE_CONFIG)

  const requirejs = window.requirejs
  const require = window.require
  if (!require || !requirejs) throw new Error('RequireJS did not initialise')

  // The Spectra bundle config only registers the bundle map; it never defines the `oj-sp` path,
  // so any oj-sp module would 404 without this (verified against the CDN config).
  requirejs.config({
    paths: {
      'oj-sp': `https://static.oracle.com/cdn/spectra-ui/oj-sp/${SPECTRA_VERSION}`,
    },
  })

  await new Promise<void>((resolve, reject) => {
    require(OJ_MODULES, (...args: unknown[]) => {
      // ojs/ojarraydataprovider is the 3rd module and exports the class as the module value
      const ArrayDataProvider = args[2]
      window.__mateuOj = {
        ready: true,
        ArrayDataProvider,
        require,
      }
      resolve()
    }, (err: unknown) => reject(err))
  })
}

async function boot() {
  window.__mateuOj = { ready: false }
  try {
    await loadOjet()
  } catch (e) {
    // eslint-disable-next-line no-console
    console.warn('[redwood-spectra] OJET CDN not available — falling back to the base renderer.', e)
  }
  await mountLitRoot()
}

boot()
