/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.mateu.java-conventions")
    `library-publishing-conventions`
}

dependencies {
    compileOnly("org.projectlombok:lombok:1.18.30")
    annotationProcessor("org.projectlombok:lombok:1.18.30")

    testCompileOnly("org.projectlombok:lombok:1.18.30")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.30")

    api("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.4")
}

description = "dtos"

java {
    withJavadocJar()
}
