micronaut.application.name=mateu-starter
micronaut.server.port=8080

# Serve the web renderer bundled in the mateu-vaadin jar
micronaut.router.static-resources.assets.mapping=/**
micronaut.router.static-resources.assets.paths=classpath:static
