package io.mateu.dtos;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import io.swagger.v3.oas.annotations.media.Schema;

/** Parent interface for all component metadata types */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type")
@JsonSubTypes({
  @JsonSubTypes.Type(value = FormDto.class, name = "Form"),
  @JsonSubTypes.Type(value = AppDto.class, name = "App"),
  @JsonSubTypes.Type(value = CrudlDto.class, name = "Crud"),
  @JsonSubTypes.Type(value = ResultDto.class, name = "Result"),
  @JsonSubTypes.Type(value = MicroFrontendDto.class, name = "MicroFrontend"),
  @JsonSubTypes.Type(value = CardDto.class, name = "Card"),
  @JsonSubTypes.Type(value = DirectoryDto.class, name = "Directory"),
  @JsonSubTypes.Type(value = StepperDto.class, name = "Stepper"),
  @JsonSubTypes.Type(value = HorizontalLayoutDto.class, name = "HorizontalLayout"),
  @JsonSubTypes.Type(value = VerticalLayoutDto.class, name = "VerticalLayout"),
  @JsonSubTypes.Type(value = SplitLayoutDto.class, name = "SplitLayout"),
  @JsonSubTypes.Type(value = MasterDetailLayoutDto.class, name = "MasterDetailLayout"),
  @JsonSubTypes.Type(value = TabLayoutDto.class, name = "TabLayout"),
  @JsonSubTypes.Type(value = TabDto.class, name = "Tab"),
  @JsonSubTypes.Type(value = AccordionLayoutDto.class, name = "AccordionLayout"),
  @JsonSubTypes.Type(value = AccordionPanelDto.class, name = "AccordionPanel"),
  @JsonSubTypes.Type(value = FormLayoutDto.class, name = "FormLayout"),
  @JsonSubTypes.Type(value = FormRowDto.class, name = "FormRow"),
  @JsonSubTypes.Type(value = FormItemDto.class, name = "FormItem"),
  @JsonSubTypes.Type(value = ScrollerDto.class, name = "Scroller"),
  @JsonSubTypes.Type(value = FullWidthDto.class, name = "FullWidth"),
  @JsonSubTypes.Type(value = ContainerDto.class, name = "Container"),
  @JsonSubTypes.Type(value = ElementDto.class, name = "Element"),
  @JsonSubTypes.Type(value = FormFieldDto.class, name = "FormField"),
  @JsonSubTypes.Type(value = TextDto.class, name = "Text"),
  @JsonSubTypes.Type(value = AvatarDto.class, name = "Avatar"),
  @JsonSubTypes.Type(value = AvatarGroupDto.class, name = "AvatarGroup"),
  @JsonSubTypes.Type(value = BadgeDto.class, name = "Badge"),
  @JsonSubTypes.Type(value = AnchorDto.class, name = "Anchor"),
  @JsonSubTypes.Type(value = ButtonDto.class, name = "Button"),
  @JsonSubTypes.Type(value = ChartDto.class, name = "Chart"),
  @JsonSubTypes.Type(value = BpmnDto.class, name = "Bpmn"),
  @JsonSubTypes.Type(value = WorkflowDto.class, name = "Workflow"),
  @JsonSubTypes.Type(value = WorkflowElkDto.class, name = "WorkflowElk"),
  @JsonSubTypes.Type(value = FormEditorDto.class, name = "FormEditor"),
  @JsonSubTypes.Type(value = IconDto.class, name = "Icon"),
  @JsonSubTypes.Type(value = ConfirmDialogDto.class, name = "ConfirmDialog"),
  @JsonSubTypes.Type(value = ContextMenuDto.class, name = "ContextMenu"),
  @JsonSubTypes.Type(value = CookieConsentDto.class, name = "CookieConsent"),
  @JsonSubTypes.Type(value = DetailsDto.class, name = "Details"),
  @JsonSubTypes.Type(value = DialogDto.class, name = "Dialog"),
  @JsonSubTypes.Type(value = DrawerDto.class, name = "Drawer"),
  @JsonSubTypes.Type(value = ImageDto.class, name = "Image"),
  @JsonSubTypes.Type(value = MapDto.class, name = "Map"),
  @JsonSubTypes.Type(value = MarkdownDto.class, name = "Markdown"),
  @JsonSubTypes.Type(value = NotificationDto.class, name = "Notification"),
  @JsonSubTypes.Type(value = ProgressBarDto.class, name = "ProgressBar"),
  @JsonSubTypes.Type(value = PopoverDto.class, name = "Popover"),
  @JsonSubTypes.Type(value = TooltipDto.class, name = "Tooltip"),
  @JsonSubTypes.Type(value = MessageInputDto.class, name = "MessageInput"),
  @JsonSubTypes.Type(value = MessageListDto.class, name = "MessageList"),
  @JsonSubTypes.Type(value = CustomFieldDto.class, name = "CustomField"),
  @JsonSubTypes.Type(value = MenuBarDto.class, name = "MenuBar"),
  @JsonSubTypes.Type(value = GridDto.class, name = "Grid"),
  @JsonSubTypes.Type(value = GridColumnDto.class, name = "GridColumn"),
  @JsonSubTypes.Type(value = VirtualListDto.class, name = "VirtualList"),
  @JsonSubTypes.Type(value = BoardLayoutDto.class, name = "BoardLayout"),
  @JsonSubTypes.Type(value = BoardLayoutRowDto.class, name = "BoardLayoutRow"),
  @JsonSubTypes.Type(value = BoardLayoutItemDto.class, name = "BoardLayoutItem"),
  @JsonSubTypes.Type(value = BreadcrumbsDto.class, name = "Breadcrumbs"),
  @JsonSubTypes.Type(value = BreadcrumbDto.class, name = "Breadcrumb"),
  @JsonSubTypes.Type(value = CarouselLayoutDto.class, name = "CarouselLayout"),
  @JsonSubTypes.Type(value = DivDto.class, name = "Div"),
  @JsonSubTypes.Type(value = FormSectionDto.class, name = "FormSection"),
  @JsonSubTypes.Type(value = FormSubSectionDto.class, name = "FormSubSection"),
  @JsonSubTypes.Type(value = PageDto.class, name = "Page"),
  @JsonSubTypes.Type(value = ChatDto.class, name = "Chat"),
  @JsonSubTypes.Type(value = MetricCardDto.class, name = "MetricCard"),
  @JsonSubTypes.Type(value = ScoreboardDto.class, name = "Scoreboard"),
  @JsonSubTypes.Type(value = DashboardPanelDto.class, name = "DashboardPanel"),
  @JsonSubTypes.Type(value = DashboardLayoutDto.class, name = "DashboardLayout"),
  @JsonSubTypes.Type(value = FoldoutLayoutDto.class, name = "FoldoutLayout"),
  @JsonSubTypes.Type(value = HeroSectionDto.class, name = "HeroSection"),
  @JsonSubTypes.Type(value = EmptyStateDto.class, name = "EmptyState"),
  @JsonSubTypes.Type(value = SkeletonDto.class, name = "Skeleton"),
  @JsonSubTypes.Type(value = GanttDto.class, name = "Gantt"),
  @JsonSubTypes.Type(value = KanbanDto.class, name = "Kanban"),
  @JsonSubTypes.Type(value = TimelineDto.class, name = "Timeline"),
  @JsonSubTypes.Type(value = ProgressStepsDto.class, name = "ProgressSteps"),
  @JsonSubTypes.Type(value = StatDto.class, name = "Stat"),
  @JsonSubTypes.Type(value = CalendarDto.class, name = "Calendar"),
  @JsonSubTypes.Type(value = PricingTableDto.class, name = "PricingTable"),
  @JsonSubTypes.Type(value = OrgChartDto.class, name = "OrgChart"),
  @JsonSubTypes.Type(value = HeatmapDto.class, name = "Heatmap"),
  @JsonSubTypes.Type(value = FunnelDto.class, name = "Funnel"),
  @JsonSubTypes.Type(value = TrendChartDto.class, name = "TrendChart"),
  @JsonSubTypes.Type(value = FeatureGridDto.class, name = "FeatureGrid"),
  @JsonSubTypes.Type(value = TestimonialsDto.class, name = "Testimonials"),
  @JsonSubTypes.Type(value = FaqDto.class, name = "Faq"),
  @JsonSubTypes.Type(value = CalloutCardDto.class, name = "CalloutCard"),
  @JsonSubTypes.Type(value = CommentThreadDto.class, name = "CommentThread"),
  @JsonSubTypes.Type(value = FileListDto.class, name = "FileList"),
  @JsonSubTypes.Type(value = ChecklistDto.class, name = "Checklist")
})
@Schema(
    oneOf = {
      FormDto.class,
      AppDto.class,
      CrudlDto.class,
      ResultDto.class,
      MicroFrontendDto.class,
      CardDto.class,
      DirectoryDto.class,
      StepperDto.class,
      HorizontalLayoutDto.class,
      VerticalLayoutDto.class,
      SplitLayoutDto.class,
      MasterDetailLayoutDto.class,
      TabLayoutDto.class,
      TabDto.class,
      AccordionLayoutDto.class,
      AccordionPanelDto.class,
      FormLayoutDto.class,
      ScrollerDto.class,
      FullWidthDto.class,
      ContainerDto.class,
      ElementDto.class,
      FormFieldDto.class,
      TextDto.class,
      AvatarDto.class,
      AvatarGroupDto.class,
      BadgeDto.class,
      BreadcrumbsDto.class,
      BreadcrumbDto.class,
      AnchorDto.class,
      ButtonDto.class,
      ChartDto.class,
      BpmnDto.class,
      IconDto.class,
      ConfirmDialogDto.class,
      ContextMenuDto.class,
      CookieConsentDto.class,
      DetailsDto.class,
      DialogDto.class,
      DrawerDto.class,
      ImageDto.class,
      MapDto.class,
      MarkdownDto.class,
      NotificationDto.class,
      ProgressBarDto.class,
      PopoverDto.class,
      TooltipDto.class,
      MessageInputDto.class,
      MessageListDto.class,
      CustomFieldDto.class,
      MenuBarDto.class,
      GridDto.class,
      GridColumnDto.class,
      VirtualListDto.class,
      BoardLayoutDto.class,
      BoardLayoutRowDto.class,
      BoardLayoutItemDto.class,
      CarouselLayoutDto.class,
      DivDto.class,
      FormSectionDto.class,
      FormSubSectionDto.class,
      PageDto.class,
      ChatDto.class,
      WorkflowElkDto.class,
      FormEditorDto.class,
      MetricCardDto.class,
      ScoreboardDto.class,
      DashboardPanelDto.class,
      DashboardLayoutDto.class,
      FoldoutLayoutDto.class,
      HeroSectionDto.class,
      EmptyStateDto.class,
      SkeletonDto.class,
      GanttDto.class,
      KanbanDto.class,
      TimelineDto.class,
      ProgressStepsDto.class,
      StatDto.class,
      CalendarDto.class,
      PricingTableDto.class,
      OrgChartDto.class,
      HeatmapDto.class,
      FunnelDto.class,
      TrendChartDto.class,
      FeatureGridDto.class,
      TestimonialsDto.class,
      FaqDto.class,
      CalloutCardDto.class,
      CommentThreadDto.class,
      FileListDto.class,
      ChecklistDto.class
    })
public interface ComponentMetadataDto {}
