/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.mateu.java-conventions")
    `library-publishing-conventions`
}

dependencies {
    api("org.freemarker:freemarker:2.3.31")
    api("com.google.auto.service:auto-service:1.1.1")
}

description = "annotation-processing"

java {
    withJavadocJar()
}
