/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.mateu.java-conventions")
}

dependencies {
    api(project(":core"))

    compileOnly("org.projectlombok:lombok:1.18.30")
    annotationProcessor("org.projectlombok:lombok:1.18.30")

    testCompileOnly("org.projectlombok:lombok:1.18.30")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.30")

    compileOnly("org.springframework.boot:spring-boot-starter-webflux:3.0.5")
}

description = "embedded-front"

java {
    withJavadocJar()
}
