/**
 * The words of the client's own CHROME — everything Mateu draws by itself rather than receiving from
 * the server: toolbar and dialog buttons, the filter bar, pagination, empty states, the command
 * center, error toasts, field widgets (upload, signature, camera…), aria-labels. The app's own texts
 * come from the server (already translated by its Translator); these are the rest, and they used to
 * be a mix ("Cerrar" next to "Command center" next to "Send").
 *
 * ONE catalogue: every chrome string lives here, in every language, and components read it with
 * {@link chromeText} / {@link chromeTextf}. A test keeps it that way (chromeTexts.lint.test.ts fails
 * on a new hard-coded chrome string in the main components) and checks every language has every key.
 *
 * The language is the page's `<html lang>` — which `applyUiLanguage` sets from the server
 * (`AppDto.locale`, i.e. the app's Translator), else the browser's. Spanish and English for now; any
 * other language falls back to English. Adding a language = adding one more block below.
 */
const en = {
    // app shell & chat
    chat: 'Assistant',
    openChat: 'Open the assistant',
    closeChat: 'Close the assistant',
    darkMode: 'Switch to dark mode',
    lightMode: 'Switch to light mode',
    expandChat: 'Expand',
    collapseChat: 'Restore size',
    chatEmpty: 'Ask whatever you need: about this screen, your data or how to do something.',
    chatPlaceholder: 'Write a message…',
    send: 'Send',
    attachFiles: 'Attach files',
    toolsUsed: 'Tools used',
    sections: 'Sections',
    menu: 'Menu',
    back: 'Back',
    searchMenu: 'Search…',
    goTo: 'Go to…',
    noResultsFor: 'No results for "{query}"',
    skipToContent: 'Skip to content',
    breadcrumb: 'Breadcrumb',
    moreActions: 'More actions',
    // confirmations & generic actions
    confirmTitle: 'One moment, please',
    confirmMessage: 'Are you sure?',
    confirmYes: 'Yes',
    confirmNo: 'No',
    ok: 'OK',
    cancel: 'Cancel',
    close: 'Close',
    dismiss: 'Dismiss',
    retry: 'Retry',
    undo: 'Undo',
    save: 'Save',
    apply: 'Apply',
    clear: 'Clear',
    reset: 'Reset',
    remove: 'Remove',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    select: 'Select',
    view: 'View',
    copy: 'Copy',
    yes: 'Yes',
    no: 'No',
    forbidden: 'You are not allowed to do this.',
    notFound: 'Not found',
    notFoundMessage: 'It may have been deleted, or the link is wrong.',
    goBack: 'Go back',
    // navigation inside a component
    previous: 'Previous',
    next: 'Next',
    expand: 'Expand',
    collapse: 'Collapse',
    maximize: 'Maximize',
    fold: 'Fold',
    showAll: 'Show all',
    showMore: 'Show more',
    panels: 'Panels',
    firstPage: 'First page',
    previousPage: 'Previous page',
    nextPage: 'Next page',
    lastPage: 'Last page',
    // listings & filters
    search: 'Search',
    filterBy: 'Filter by',
    clearFilters: 'Clear filters',
    savedViews: 'Saved views',
    noSavedViews: 'No saved views yet',
    saveViewAs: 'Save current view as…',
    fixedByPage: 'Fixed by the page',
    rangeFrom: 'From',
    rangeTo: 'To',
    columns: 'Columns',
    moveUp: 'Move up',
    moveDown: 'Move down',
    moveColumnUp: 'Move {column} up',
    moveColumnDown: 'Move {column} down',
    addRow: 'Add row',
    removeRow: 'Remove row',
    toggleDetails: 'Toggle details',
    noData: 'No data.',
    nothingHere: 'Nothing here yet.',
    loading: 'Loading…',
    loadingMore: 'Loading more…',
    import: 'Import',
    // field widgets
    upload: 'Upload',
    replace: 'Replace',
    chooseFile: 'Choose file',
    capture: 'Capture',
    accept: 'Accept',
    signAgain: 'Sign again',
    dropHere: 'Drop here',
    noEvents: 'No events',
    calendarView: 'View',
    less: 'Less',
    more: 'More',
    // notifications
    notifications: 'Notifications',
    noNotifications: 'No notifications',
    markAllRead: 'Mark all read',
    // command center
    commandCenter: 'Command center',
    commandCenterHint: 'Search and navigate (⌘K)',
    commandCenterPlaceholder: 'Search screens, data and actions…',
    screens: 'Screens',
    recent: 'Recent',
    noMenuOptions: 'No menu options.',
    askAi: 'Ask AI: “{query}”',
    noMatchesFor: 'No matches for “{query}”.',
    // chat panel (chatTexts.ts maps its keys onto these)
    chatWiden: 'Widen the assistant',
    chatRestoreWidth: 'Restore the width',
    chatResize: 'Assistant width',
    chatDictate: 'Dictate',
    chatStopDictation: 'Stop dictation',
    chatThinking: 'Thinking…',
    chatAnswering: 'Answering…',
    chatCallingTool: 'Calling {name}…',
    chatAgentError: 'Unknown agent error',
    chatYou: 'You',
    chatServerError: 'The server answered {status}: {error}',
    chatNoAnswer: '⚠️ The agent returned no answer. Check that the LLM is configured correctly (API key).',
    chatConnectionClosed: '⚠️ No answer from the agent. The server closed the connection without sending data — check that the LLM has its API key configured and is available.',
    chatErrorPrefix: '⚠️ Error: ',
    sectionUnavailable: '{name} is not available right now. It will be retried.',
    selection: 'Selection',
    selectedItems: '{count} selected items',
    // rich text editor
    formatting: 'Formatting',
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    strikethrough: 'Strikethrough',
    heading: 'Heading',
    bulletedList: 'Bulleted list',
    numberedList: 'Numbered list',
    quote: 'Quote',
    codeBlock: 'Code block',
    link: 'Link',
    linkAddress: 'Link address',
    // misc components
    newRecord: 'New',
    task: 'Task',
    resource: 'Resource',
    recommended: 'Recommended',
    selectRowForDetails: 'Select a row to view details.',
    selectItemForDetails: 'Select an item to view details',
    dragToRearrange: 'Drag to rearrange (Alt+← / Alt+→)',
    unsetDefaultView: 'Unset as default',
    openWithView: 'Open this listing with this view',
    cookiesMessage: 'This website uses cookies.',
    cookiesDismiss: 'Ok. Thanks :).',
    // messages
    unsavedChanges: 'You have unsaved changes. Are you sure you want to leave this page?',
    selectRowsFirst: 'You first need to select some rows',
    validationErrors: 'There are validation errors',
    requestFailed: 'Request failed{status}',
    actionFailed: 'The action failed: {error}',
    repeatingRequest: 'A repeating request was detected and stopped to protect the server. Reload the page or navigate elsewhere.',
    offlineBanner: 'No connection — changes you make now will not be saved.',
    connectionRestored: 'Connection restored.',
    failOffline: 'No connection. Your changes have not been sent — check your network and try again.',
    failTimeout: 'The server is taking too long to answer. Your changes may not have been saved.',
    failServer: 'The server could not complete the request{status}. Please try again.',
    failUnauthorized: 'Your session is no longer valid. Please sign in again.',
    failNotFound: 'This is no longer available. It may have been moved or deleted.',
    failClient: 'The request was rejected{status}.',
    failUnknown: 'Something went wrong. Please try again.',
    errorStatus: ' (error {status})',
}

type Catalogue = Record<keyof typeof en, string>

const es: Catalogue = {
    chat: 'Asistente',
    openChat: 'Abrir el asistente',
    closeChat: 'Cerrar el asistente',
    darkMode: 'Cambiar a modo oscuro',
    lightMode: 'Cambiar a modo claro',
    expandChat: 'Ampliar',
    collapseChat: 'Tamaño normal',
    chatEmpty: 'Pregunta lo que necesites: sobre esta pantalla, tus datos o cómo hacer algo.',
    chatPlaceholder: 'Escribe un mensaje…',
    send: 'Enviar',
    attachFiles: 'Adjuntar ficheros',
    toolsUsed: 'Herramientas usadas',
    sections: 'Secciones',
    menu: 'Menú',
    back: 'Volver',
    searchMenu: 'Buscar…',
    goTo: 'Ir a…',
    noResultsFor: 'Sin resultados para "{query}"',
    skipToContent: 'Saltar al contenido',
    breadcrumb: 'Ruta de navegación',
    moreActions: 'Más acciones',
    confirmTitle: 'Un momento',
    confirmMessage: '¿Seguro?',
    confirmYes: 'Sí',
    confirmNo: 'No',
    ok: 'Aceptar',
    cancel: 'Cancelar',
    close: 'Cerrar',
    dismiss: 'Descartar',
    retry: 'Reintentar',
    undo: 'Deshacer',
    save: 'Guardar',
    apply: 'Aplicar',
    clear: 'Limpiar',
    reset: 'Restablecer',
    remove: 'Quitar',
    delete: 'Eliminar',
    edit: 'Editar',
    add: 'Añadir',
    select: 'Seleccionar',
    view: 'Ver',
    copy: 'Copiar',
    yes: 'Sí',
    no: 'No',
    forbidden: 'No tienes permiso para esta acción.',
    notFound: 'No encontrado',
    notFoundMessage: 'Puede que se haya borrado o que el enlace no sea correcto.',
    goBack: 'Volver',
    previous: 'Anterior',
    next: 'Siguiente',
    expand: 'Expandir',
    collapse: 'Contraer',
    maximize: 'Maximizar',
    fold: 'Plegar',
    showAll: 'Ver todo',
    showMore: 'Ver más',
    panels: 'Paneles',
    firstPage: 'Primera página',
    previousPage: 'Página anterior',
    nextPage: 'Página siguiente',
    lastPage: 'Última página',
    search: 'Buscar',
    filterBy: 'Filtrar por',
    clearFilters: 'Quitar filtros',
    savedViews: 'Vistas guardadas',
    noSavedViews: 'Aún no hay vistas guardadas',
    saveViewAs: 'Guardar la vista actual como…',
    fixedByPage: 'Fijado por la página',
    rangeFrom: 'Desde',
    rangeTo: 'Hasta',
    columns: 'Columnas',
    moveUp: 'Subir',
    moveDown: 'Bajar',
    moveColumnUp: 'Subir {column}',
    moveColumnDown: 'Bajar {column}',
    addRow: 'Añadir fila',
    removeRow: 'Quitar fila',
    toggleDetails: 'Mostrar u ocultar el detalle',
    noData: 'Sin datos.',
    nothingHere: 'Aún no hay nada aquí.',
    loading: 'Cargando…',
    loadingMore: 'Cargando más…',
    import: 'Importar',
    upload: 'Subir',
    replace: 'Reemplazar',
    chooseFile: 'Elegir fichero',
    capture: 'Capturar',
    accept: 'Aceptar',
    signAgain: 'Firmar de nuevo',
    dropHere: 'Suelta aquí',
    noEvents: 'Sin eventos',
    calendarView: 'Vista',
    less: 'Menos',
    more: 'Más',
    notifications: 'Notificaciones',
    noNotifications: 'Sin notificaciones',
    markAllRead: 'Marcar todo como leído',
    commandCenter: 'Centro de mando',
    commandCenterHint: 'Buscar y navegar (⌘K)',
    commandCenterPlaceholder: 'Buscar pantallas, datos y acciones…',
    screens: 'Pantallas',
    recent: 'Recientes',
    noMenuOptions: 'Sin opciones de menú.',
    askAi: 'Preguntar a la IA: “{query}”',
    noMatchesFor: 'No encontramos coincidencias para “{query}”.',
    chatWiden: 'Ampliar el asistente',
    chatRestoreWidth: 'Ancho normal',
    chatResize: 'Ancho del asistente',
    chatDictate: 'Dictar',
    chatStopDictation: 'Detener dictado',
    chatThinking: 'Pensando…',
    chatAnswering: 'Respondiendo…',
    chatCallingTool: 'Llamando a {name}…',
    chatAgentError: 'Error desconocido del agente',
    chatYou: 'Tú',
    chatServerError: 'El servidor respondió {status}: {error}',
    chatNoAnswer: '⚠️ El agente no devolvió ninguna respuesta. Comprueba que el LLM está configurado correctamente (API key).',
    chatConnectionClosed: '⚠️ No se recibió respuesta del agente. El servidor cerró la conexión sin enviar datos — comprueba que el LLM tiene la API key configurada y está disponible.',
    chatErrorPrefix: '⚠️ Error: ',
    sectionUnavailable: '{name} no está disponible ahora. Se volverá a intentar.',
    selection: 'Selección',
    selectedItems: '{count} elementos seleccionados',
    formatting: 'Formato',
    bold: 'Negrita',
    italic: 'Cursiva',
    underline: 'Subrayado',
    strikethrough: 'Tachado',
    heading: 'Encabezado',
    bulletedList: 'Lista con viñetas',
    numberedList: 'Lista numerada',
    quote: 'Cita',
    codeBlock: 'Bloque de código',
    link: 'Enlace',
    linkAddress: 'Dirección del enlace',
    newRecord: 'Nuevo',
    task: 'Tarea',
    resource: 'Recurso',
    recommended: 'Recomendado',
    selectRowForDetails: 'Selecciona una fila para ver el detalle.',
    selectItemForDetails: 'Selecciona un elemento para ver el detalle',
    dragToRearrange: 'Arrastra para reordenar (Alt+← / Alt+→)',
    unsetDefaultView: 'Dejar de usar por defecto',
    openWithView: 'Abrir este listado con esta vista',
    cookiesMessage: 'Este sitio web usa cookies.',
    cookiesDismiss: 'Entendido, gracias.',
    unsavedChanges: 'Tienes cambios sin guardar. ¿Seguro que quieres salir de esta página?',
    selectRowsFirst: 'Primero selecciona alguna fila',
    validationErrors: 'Hay errores de validación',
    requestFailed: 'La petición falló{status}',
    actionFailed: 'La acción falló: {error}',
    repeatingRequest: 'Se detectó una petición repetida y se detuvo para proteger el servidor. Recarga la página o navega a otra.',
    offlineBanner: 'Sin conexión: lo que cambies ahora no se guardará.',
    connectionRestored: 'Conexión restablecida.',
    failOffline: 'Sin conexión. Tus cambios no se han enviado: revisa la red e inténtalo de nuevo.',
    failTimeout: 'El servidor tarda demasiado en responder. Puede que tus cambios no se hayan guardado.',
    failServer: 'El servidor no pudo completar la petición{status}. Inténtalo de nuevo.',
    failUnauthorized: 'Tu sesión ya no es válida. Vuelve a iniciar sesión.',
    failNotFound: 'Esto ya no está disponible. Puede que se haya movido o borrado.',
    failClient: 'La petición fue rechazada{status}.',
    failUnknown: 'Algo ha ido mal. Inténtalo de nuevo.',
    errorStatus: ' (error {status})',
}

const TEXTS: Record<'en' | 'es', Catalogue> = { en, es }

export type ChromeTextKey = keyof typeof en

/** The languages the catalogue has (for tests and tooling). */
export const CHROME_LANGUAGES = Object.keys(TEXTS) as ('en' | 'es')[]

/** The catalogue of one language (for tests and tooling). */
export const chromeCatalogue = (lang: 'en' | 'es'): Readonly<Catalogue> => TEXTS[lang]

export const chromeLanguage = (explicit?: string): 'es' | 'en' => {
    const lang = explicit || (typeof document !== 'undefined' && document.documentElement?.lang)
        || (typeof navigator !== 'undefined' && navigator.language) || ''
    return lang.toLowerCase().startsWith('es') ? 'es' : 'en'
}

export const chromeText = (key: ChromeTextKey, lang?: string): string => TEXTS[chromeLanguage(lang)][key]

/** {@link chromeText} with `{name}` placeholders filled from `vars`. */
export const chromeTextf = (key: ChromeTextKey, vars: Record<string, unknown>, lang?: string): string =>
    chromeText(key, lang).replace(/\{(\w+)\}/g, (m, name: string) => (name in vars ? String(vars[name] ?? '') : m))

/**
 * Sets the page language (`<html lang>`): the server's when it says one (`AppDto.locale`, the app's
 * Translator), else — on boot, when the page declares none — the browser's. Screen readers,
 * hyphenation, spell-check and the chrome catalogue all read it. Returns the language in effect.
 */
export const applyUiLanguage = (serverLocale?: string | null): string => {
    if (typeof document === 'undefined') return serverLocale || 'en'
    const root = document.documentElement
    if (serverLocale && serverLocale.trim()) {
        if (root.lang !== serverLocale) root.lang = serverLocale
    } else if (!root.lang) {
        root.lang = (typeof navigator !== 'undefined' && navigator.language) || 'en'
    }
    return root.lang
}
