/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.mateu.java-conventions")
    `library-publishing-conventions`
}

dependencies {
    api(project(":core"))
    compileOnly("org.springframework.boot:spring-boot-starter-data-jpa:3.0.5")

    compileOnly("org.projectlombok:lombok:1.18.30")
    annotationProcessor("org.projectlombok:lombok:1.18.30")

    testCompileOnly("org.projectlombok:lombok:1.18.30")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.30")
}

description = "jpa"

java {
    withJavadocJar()
}
