############# English navigation ##############

# main menu

[[main]]
name = "Java"
url = "java-user-manual/"
weight = 1

[[main]]
name = "Kotlin"
url = "kotlin-user-manual/"
weight = 2

[[main]]
name = "C#"
url = "csharp-user-manual/"
weight = 3

[[main]]
name = "Python"
url = "python-user-manual/"
weight = 4

[[main]]
name = "Design systems"
url = "design-systems/"
weight = 5

[[main]]
name = "Native"
url = "native/"
weight = 6

#[[main]]
#name = "Faq"
#url = "faq/"
#weight = 2

#[[main]]
#name = "Elements"
#url = "getting-started/elements/"
#weight = 3

# footer menu
[[footer_primary]]
name = "GitHub repo"
url = "https://github.com/miguelperezcolom/mateu"
weight = 1

#[[footer_primary]]
#name = "Contact us"
#url = "contact/"
#weight = 2

# footer menu
#[[footer_secondary]]
#name = "Privacy Policy"
#url = "privacy-policy/"
#weight = 1

#[[footer_secondary]]
#name = "Terms And Conditions"
#url = "terms-conditions/"
#weight = 2
