#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
logo_darkmode = "images/logo-darkmode.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "160px"
logo_height = "32px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "docbox"
# contact form action
contact_form_action = "#" # contact form works with [https://airform.io/] or [https://formspree.io]
# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX
google_adsense = ""     # example: ca-pub-xxxxxxxxxxxxxxxx
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""
# copyright
theme_copyright = true
copyright = "© Copyright 2023 COMPANY"

# Table of Contents 
tableofcontents = true

# Preloader
[preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[[navigation_button]]
enable = true
label = "Changelog"
link = "changelog/"

[[navigation_button]]
enable = true
label = "Contact Us"
link = "contact/"

# search - https://github.com/gethugothemes/hugo-modules/tree/master/search
[search]
enable = true
primary_color = "#222"
include_all_sections = true
show_image = false

# contact info
[contact_info]
mobile = "415 509 6995"
email = "hello@docbox.com"
address = "2118 Thornridge Cir. Syracuse, Connecticut 35624"

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["Boilerplate", "Hugo"]
description = "Hugo & Tailwindcss Starter"
author = "gethugothemes"
image = ""


# site verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code
mastodon = "" # Your verification code

# cookies
[cookies]
enable = true
expire_days = 60
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# Subscription
[subscription]
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"