/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.mateu.java-conventions")
    `library-publishing-conventions`
}

dependencies {
    api(project(":core"))
    api("org.springframework.boot:spring-boot-starter-security:3.0.5")
    compileOnly("org.springframework.boot:spring-boot-starter-webflux:3.0.5")
}

description = "springbooot-security"

java {
    withJavadocJar()
}
