micronaut.application.name=micronaut-app1
micronaut.server.port=8083

micronaut.router.static-resources.assets.mapping=/**
micronaut.router.static-resources.assets.paths=classpath:static

micronaut.server.cors.enabled=true
