#!/usr/bin/env bash
#
# Fails when a renderer's committed bundle is OLDER than the source it is built from.
#
# Why this exists: the committed bundles are derived artifacts regenerated BY HAND (`npm run copy`),
# and CI builds the backend from them without recompiling the TypeScript. On 2026-08-11 a fix landed
# in the source and the bundle was not regenerated, so every e2e run for the next weeks exercised
# the pre-fix frontend. The required check went red, stayed red, and merging past it became routine
# — which is worse than the original bug, because a real regression would have hidden inside it.
#
# Why an ancestry check and not "rebuild and diff": a byte comparison of minified output is hostage
# to build nondeterminism (toolchain version, plugin order), and a check that fails for reasons
# nobody can act on gets ignored — exactly the failure mode this is meant to prevent. Ancestry is
# deterministic, instant, and encodes the real invariant: the bundle must have been built from a
# commit at or after the last source change.
#
# Usage: scripts/check-bundle-freshness.sh
set -euo pipefail

status=0

# bundle path : source paths it is built from (space separated)
check() {
  local name="$1" bundle="$2" sources="$3"

  local bundle_commit
  bundle_commit=$(git log -1 --format=%H -- "$bundle")
  if [ -z "$bundle_commit" ]; then
    echo "?? $name: no commit found for $bundle — skipping"
    return
  fi

  # The newest source commit, ignoring test files (they do not end up in the bundle).
  local source_commit
  source_commit=$(git log -1 --format=%H -- $sources ':(exclude)**/*.test.ts' ':(exclude)**/*.spec.ts')
  if [ -z "$source_commit" ]; then
    echo "?? $name: no commit found for its sources — skipping"
    return
  fi

  # Fresh when the last source change is an ancestor of (or the same as) the last bundle change.
  if git merge-base --is-ancestor "$source_commit" "$bundle_commit"; then
    echo "OK $name: bundle is at or after its source"
  else
    status=1
    echo
    echo "STALE  $name"
    echo "  the bundle was last built at   $(git log -1 --format='%h %ad %s' --date=short "$bundle_commit")"
    echo "  but its source changed since   $(git log -1 --format='%h %ad %s' --date=short "$source_commit")"
    echo
    echo "  CI builds the backend from the COMMITTED bundle, so those source changes are not"
    echo "  running anywhere. Regenerate and commit it:"
    echo
    echo "    cd frontend/web/monorepo/apps/$name && npm run copy"
    echo
  fi
}

check vaadin \
  "backend/shared/frontend/vaadin-lit/src/main/resources/static/assets/mateu-vaadin.js" \
  "frontend/web/monorepo/apps/vaadin/src frontend/web/monorepo/libs/mateu/src"

check redwood \
  "backend/shared/frontend/redwood/src/main/resources/static" \
  "frontend/web/monorepo/apps/redwood/poc frontend/web/monorepo/apps/redwood/webApps"

exit $status
