package io.mateu.uidl.schema;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeSet;
import org.junit.jupiter.api.Test;

/**
 * {@code uidl-schema.json} is the public authoring contract (editors point their YAML IntelliSense
 * at the raw file on master), so it must never drift from the component catalog. It is generated by
 * {@link UidlSchemaGenerator} and pinned here: adding a component without regenerating fails the
 * build instead of silently shipping a schema that does not know about it.
 *
 * <p>To regenerate after adding or changing a component:
 *
 * <pre>mvn -pl shared/uidl test -Dtest=UidlSchemaTest -Duidl.schema.write=true</pre>
 */
class UidlSchemaTest {

  private static final ObjectMapper MAPPER = new ObjectMapper();

  /** The checked-in schema, at the root of the uidl module. */
  private static Path schemaFile() {
    return Path.of(System.getProperty("user.dir")).resolve("uidl-schema.json");
  }

  /** The route registry's schema, alongside it. */
  private static Path routesSchemaFile() {
    return Path.of(System.getProperty("user.dir")).resolve("routes-schema.json");
  }

  /** The mount descriptor's schema ({@code type: UI}), alongside the others. */
  private static Path mountSchemaFile() {
    return Path.of(System.getProperty("user.dir")).resolve("mount-schema.json");
  }

  @Test
  void theCheckedInMountSchemaMatchesTheMountDescriptor() throws IOException {
    var generated = UidlSchemaGenerator.generateMount();

    if (Boolean.getBoolean("uidl.schema.write")) {
      UidlSchemaGenerator.write(mountSchemaFile(), generated);
      return;
    }

    assertThat(MAPPER.readTree(Files.readString(mountSchemaFile())))
        .as("mount-schema.json is stale — regenerate it (see this class's javadoc)")
        .isEqualTo(generated);
  }

  /** The unified specs/ui authoring schema (one schema per specs/ui file, `type`-discriminated). */
  private static Path specsSchemaFile() {
    return Path.of(System.getProperty("user.dir")).resolve("specs-schema.json");
  }

  @Test
  void theCheckedInSpecsSchemaUnifiesEveryFileKind() throws IOException {
    var generated = UidlSchemaGenerator.generateSpecs();

    if (Boolean.getBoolean("uidl.schema.write")) {
      UidlSchemaGenerator.write(specsSchemaFile(), generated);
      return;
    }

    // The unified schema must offer all four branches (mount, routes envelope, bare list,
    // component)
    // and carry the defs it references (RouteEntry + the component catalog).
    assertThat(generated.get("oneOf")).hasSize(4);
    assertThat(generated.get("$defs").has("RouteEntry")).isTrue();
    assertThat(generated.get("$defs").has("Component")).isTrue();
    assertThat(MAPPER.readTree(Files.readString(specsSchemaFile())))
        .as("specs-schema.json is stale — regenerate it (see this class's javadoc)")
        .isEqualTo(generated);
  }

  @Test
  void theCheckedInRoutesSchemaMatchesTheRouteEntryRecord() throws IOException {
    var generated = UidlSchemaGenerator.generateRoutes();

    if (Boolean.getBoolean("uidl.schema.write")) {
      UidlSchemaGenerator.write(routesSchemaFile(), generated);
      return;
    }

    assertThat(MAPPER.readTree(Files.readString(routesSchemaFile())))
        .as("routes-schema.json is stale — regenerate it (see this class's javadoc)")
        .isEqualTo(generated);
  }

  @Test
  void theRoutesSchemaDescribesBothShapesTheLoaderAccepts() {
    // A routes.yaml may be a `routes:` envelope or a bare list; a schema that knew only one would
    // flag valid files as errors in the editor.
    var oneOf = UidlSchemaGenerator.generateRoutes().get("oneOf");
    assertThat(oneOf).hasSize(2);
    assertThat(oneOf.get(0).get("type").asText()).isEqualTo("object");
    assertThat(oneOf.get(1).get("type").asText()).isEqualTo("array");
  }

  @Test
  void theRoutesSchemaCoversEveryFieldOfARouteEntry() {
    var properties =
        UidlSchemaGenerator.generateRoutes().get("$defs").get("RouteEntry").get("properties");
    assertThat(properties.fieldNames())
        .toIterable()
        .containsExactlyInAnyOrder(
            "route", "definition", "viewModel", "fixedParams", "defaultParams");
  }

  @Test
  void theCheckedInSchemaMatchesTheComponentCatalog() throws IOException {
    var generated = UidlSchemaGenerator.generate();

    if (Boolean.getBoolean("uidl.schema.write")) {
      UidlSchemaGenerator.write(schemaFile());
      return;
    }

    var checkedIn = MAPPER.readTree(Files.readString(schemaFile()));

    // Report the catalog difference first: it is the failure people actually hit, and a raw tree
    // diff of 150 definitions says nothing useful about which component was forgotten.
    var generatedDefs = new TreeSet<String>();
    generated.get("$defs").fieldNames().forEachRemaining(generatedDefs::add);
    var checkedInDefs = new TreeSet<String>();
    checkedIn.get("$defs").fieldNames().forEachRemaining(checkedInDefs::add);

    var missing = new ArrayList<>(generatedDefs);
    missing.removeAll(checkedInDefs);
    var stale = new ArrayList<>(checkedInDefs);
    stale.removeAll(generatedDefs);

    assertThat(missing)
        .as("types in the catalog but not in uidl-schema.json — regenerate the schema")
        .isEmpty();
    assertThat(stale)
        .as("types in uidl-schema.json that no longer exist — regenerate the schema")
        .isEmpty();
    assertThat(checkedIn)
        .as("uidl-schema.json is stale — regenerate it (see this class's javadoc)")
        .isEqualTo(generated);
  }

  @Test
  void everyAuthorableComponentIsReachableFromTheComponentUnion() {
    var generated = UidlSchemaGenerator.generate();
    var union = new TreeSet<String>();
    generated
        .get("$defs")
        .get("Component")
        .get("oneOf")
        .forEach(ref -> union.add(ref.get("$ref").asText().substring("#/$defs/".length())));

    List<String> catalog =
        UidlSchemaGenerator.componentRecords().stream().map(Class::getSimpleName).sorted().toList();

    assertThat(union)
        .as("every authorable component must be a branch of the Component union")
        .containsExactlyElementsOf(catalog);
  }

  @Test
  void theExclusionsAreDeliberateAndDocumented() {
    // A guard on the excluded set itself: shrinking it silently would widen the authoring surface
    // without anyone deciding to. Growing it should be a reviewed change too.
    assertThat(UidlSchemaGenerator.EXCLUDED)
        .containsExactlyInAnyOrder("ServerSideComponent", "ModelViewComponent", "PageView");
  }
}
