package com.example.demo;

import static org.springframework.boot.test.context.SpringBootTest.WebEnvironment.RANDOM_PORT;

import java.util.Map;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.reactive.server.WebTestClient;

/**
 * Boots the real application and exercises mateu over HTTP, to prove that spring boot webflux
 * needs no special setup: every mateu bean comes from the io.mateu:webflux-core jar and the
 * controllers are generated by the annotation processor, with a plain javac compile.
 */
@SpringBootTest(webEnvironment = RANDOM_PORT)
class MateuHttpE2eTest {

  @Autowired WebTestClient webTestClient;

  @Test
  void indexIsServedForUiRoute() {
    webTestClient
        .get()
        .uri("/counter")
        .exchange()
        .expectStatus()
        .isOk()
        .expectBody(String.class)
        .value(body -> org.assertj.core.api.Assertions.assertThat(body).contains("<mateu-ui baseUrl=\"/counter\""));
  }

  @Test
  void spaSubRouteServesTheSameIndex() {
    webTestClient
        .get()
        .uri("/counter/section1")
        .exchange()
        .expectStatus()
        .isOk()
        .expectBody(String.class)
        .value(body -> org.assertj.core.api.Assertions.assertThat(body).contains("<mateu-ui baseUrl=\"/counter\""));
  }

  @Test
  void initialLoadReturnsTheComponentTree() {
    webTestClient
        .post()
        .uri("/counter/mateu/v3/x")
        .contentType(MediaType.APPLICATION_JSON)
        .bodyValue(runActionPayload(""))
        .exchange()
        .expectStatus()
        .isOk()
        .expectBody(String.class)
        .value(
            body ->
                org.assertj.core.api.Assertions.assertThat(body)
                    .contains("\"serverSideType\":\"com.example.demo.Counter\"")
                    .contains("\"label\":\"Increment\""));
  }

  @Test
  void runActionExecutesTheActionAndReturnsTheNewState() {
    webTestClient
        .post()
        .uri("/counter/mateu/v3/x")
        .contentType(MediaType.APPLICATION_JSON)
        .bodyValue(runActionPayload("increment"))
        .exchange()
        .expectStatus()
        .isOk()
        .expectBody(String.class)
        .value(body -> org.assertj.core.api.Assertions.assertThat(body).contains("\"count\":1"));
  }

  private static Map<String, Object> runActionPayload(String actionId) {
    return Map.of(
        "componentState", Map.of(),
        "appState", Map.of(),
        "parameters", Map.of(),
        "actionId", actionId,
        "route", "/counter",
        "serverSideType", "com.example.demo.Counter");
  }
}
