export enum ComponentMetadataType {

    Element = "Element",
    MicroFrontend = "MicroFrontend",
    Form = "Form",
    TableCrud = "TableCrud",
    CardCrud = "CardCrud",
    Result = "Result",
    Card = "Card",
    Directory = "Directory",
    Stepper = "Stepper",
    HorizontalLayout = "HorizontalLayout",
    VerticalLayout = "VerticalLayout",
    SplitLayout = "SplitLayout",
    MasterDetailLayout = "MasterDetailLayout",
    TabLayout = "TabLayout",
    AccordionLayout = "AccordionLayout",
    FormLayout = "FormLayout",
    Scroller = "Scroller",
    FullWidth = "FullWidth",
    Container = "Container",
    FormField = "FormField",
    Table = "Table",
    App = "App",
    Text = "Text",
    Avatar = "Avatar",
    AvatarGroup = "AvatarGroup",
    Badge = "Badge",
    Anchor = "Anchor",
    Button = "Button",
    Chart = "Chart",


}