# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Build frontend component

on:
  workflow_call:

jobs:
  build-frontend:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build front
        run: cd frontend && npm i && npm run build && npm run copy
