# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Build and publish

on:
  workflow_dispatch:

  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          server-id: mateu-central # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v1
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Run script
        env:
          HETZNER_SSH_PUBLIC_KEY: ${{ secrets.HETZNER_SSH_PUBLIC_KEY }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.REPO_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.REPO_PASSWORD }}
          #        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          #        PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: chmod +x ./.github/scripts/*.sh && ./.github/scripts/00-all.sh
      - name: Scp demo jar to Hetzner
        uses: appleboy/scp-action@v0.1.4
        with:
          host: explorer.mateu.io
          username: root
          key: ${{ secrets.HETZNER_SSH_PUBLIC_KEY }}
          source: "demo-0.0.1-SNAPSHOT.jar"
          target: /root/mateu
      - name: Restart demo in Hetzner
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: explorer.mateu.io
          username: root
          key: ${{ secrets.HETZNER_SSH_PUBLIC_KEY }}
          script: systemctl restart mateu
