# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Deploy demo

on:
  workflow_dispatch:

jobs:
  all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Run script
        env:
          HETZNER_SSH_PUBLIC_KEY: ${{ secrets.HETZNER_SSH_PUBLIC_KEY }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.REPO_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.REPO_PASSWORD }}
          #        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          #        PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: chmod +x ./.github/scripts/*.sh && ./.github/scripts/18-deploy-to-hetzner.sh

