name: Tests pass

on: pull_request

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v1
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Build with Maven
        run: mvn -B install --file backend/pom.xml
      - name: Start demo
        run: mvn install -f demo/pom.xml && mvn spring-boot:start -f demo/pom.xml
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: cd e2e && npm ci
      - name: Install Playwright
        run: cd e2e && npx playwright install --with-deps
      - name: Run Playwright tests
        run: cd e2e && npx playwright test
        env:
          PLAYWRIGHT_TEST_BASE_URL: http://localhost:8081
      - name: Stop demo
        run: mvn spring-boot:stop -f demo/pom.xml
